# Generated by Django 2.2.10 on 2021-04-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('time_start', models.DateTimeField(verbose_name='date published')),
                ('time_end', models.DateTimeField(verbose_name='date published')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['time_start'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('TXT', 'Ответ текстом'), ('CH1', 'выбор одгого'), ('CHM', 'Выбор нескольких')], max_length=300)),
                ('pool', models.ManyToManyField(to='polls.Pool')),
            ],
            options={
                'ordering': ['text'],
            },
        ),
    ]
