# Generated by Django 2.2.10 on 2021-04-05 12:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('time_start', models.DateTimeField(verbose_name='date published')),
                ('time_end', models.DateTimeField(verbose_name='date passed')),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['time_start'],
            },
        ),
        migrations.DeleteModel(
            name='Pool',
        ),
        migrations.AlterField(
            model_name='question',
            name='pool',
            field=models.ManyToManyField(to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('TXT', 'Ответ текстом'), ('CH1', 'Выбор одгого'), ('CHM', 'Выбор нескольких')], max_length=300),
        ),
        migrations.AddField(
            model_name='answers',
            name='poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='polls.Question'),
        ),
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
