# Generated by Django 2.2.10 on 2021-04-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210405_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='time_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date passed'),
        ),
    ]
