# Generated by Django 2.2.10 on 2021-04-05 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210405_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pool',
        ),
        migrations.AddField(
            model_name='question',
            name='poll',
            field=models.ManyToManyField(related_name='questions', to='polls.Poll'),
        ),
    ]
